image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run:
  script:
    - python setup.py sdist
    - python setup.py install
  artifacts:
    paths:
      - dist/*.tar.gz
